// src/app/shared/shared.module.ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TuiTableModule, TuiTablePaginationModule, TuiTableFiltersModule } from '@taiga-ui/addon-table';
import { TuiActiveZoneModule, TuiLetModule } from '@taiga-ui/cdk';
import { ColorChromeModule } from 'ngx-color/chrome';
import { ColorTwitterModule } from 'ngx-color/twitter';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { TuiAppBarModule, TuiSidebarModule, TuiTabBarModule } from '@taiga-ui/addon-mobile';
import { TuiRootModule, TuiNotificationModule, TuiDialogModule, TuiAlertModule, TuiFormatNumberPipeModule, TuiDropdownModule, TuiTooltipModule, TuiCalendarModule, TuiLoaderModule, TuiHintModule, TuiSvgModule, TuiButtonModule, TuiScrollbarModule, TuiLabelModule, TuiDataListModule, TuiTextfieldControllerModule, TuiExpandModule } from '@taiga-ui/core';
import { TuiInputNumberModule, TuiActionModule, TuiInputModule, TuiTextAreaModule, TuiInputFilesModule, TuiInputYearModule, TuiCheckboxBlockModule, TuiMarkerIconModule, TuiAccordionModule, TuiStepperModule, TuiInputPasswordModule, TuiPaginationModule, TuiComboBoxModule, TuiCheckboxLabeledModule, TuiToggleModule, TuiTabsModule, TuiBadgeModule, TuiBadgedContentModule, TuiCarouselModule, TuiIslandModule, TuiLazyLoadingModule, TuiMultiSelectModule, TuiSelectModule, TuiDataListWrapperModule, TuiAvatarModule, TuiTagModule, TuiElasticContainerModule } from '@taiga-ui/kit';
import { NavbarComponent } from '../components/navbar/navbar.component';
import { NotificationComponent } from '../components/notification/notification.component';
import { RouterModule } from '@angular/router';
import { ScrollToNotPlayedDirective } from '../core/services/scroll-to-not-played.directive';
import { ClickOutsideDirective } from '../core/services/click-outside.directive';
import { TuiTagDirectiveDirective } from '../views/fixtures/match/tui-tag-directive.directive';

@NgModule({
    imports: [
        CommonModule,
        RouterModule,
        FontAwesomeModule,
        ColorChromeModule,
        ColorTwitterModule,
        TuiRootModule,
        TuiNotificationModule,
        TuiDialogModule,
        TuiTableModule,
        TuiTablePaginationModule,
        TuiAlertModule,
        TuiInputNumberModule,
        TuiFormatNumberPipeModule,
        TuiActionModule,
        TuiInputModule,
        TuiTextAreaModule,
        TuiInputFilesModule,
        TuiInputYearModule,
        TuiDropdownModule,
        TuiCheckboxBlockModule,
        TuiMarkerIconModule,
        TuiAccordionModule,
        TuiTooltipModule,
        TuiStepperModule,
        TuiSidebarModule,
        TuiActiveZoneModule,
        TuiInputPasswordModule,
        TuiPaginationModule,
        TuiComboBoxModule,
        TuiCheckboxLabeledModule,
        TuiToggleModule,
        TuiAppBarModule,
        TuiCalendarModule,
        TuiLoaderModule,
        TuiHintModule,
        TuiTableFiltersModule,
        TuiSvgModule,
        TuiTabsModule,
        TuiButtonModule,
        TuiTabBarModule,
        TuiBadgeModule,
        TuiBadgedContentModule,
        TuiCarouselModule,
        TuiIslandModule,
        TuiScrollbarModule,
        TuiLazyLoadingModule,
        FormsModule,
        ReactiveFormsModule,
        TuiMultiSelectModule,
        TuiSelectModule,
        TuiDataListWrapperModule,
        TuiAvatarModule,
        TuiLabelModule,
        TuiLetModule,
        TuiTagModule,
        TuiDataListModule,
        TuiTextfieldControllerModule,
        TuiDataListWrapperModule,
        TuiElasticContainerModule,
        TuiExpandModule,
        TuiInputModule,
        TuiInputFilesModule,
        TuiComboBoxModule,
        TuiDataListWrapperModule,
        TuiButtonModule,
        TuiLetModule,
        HttpClientModule,
    ],
    declarations: [
        NavbarComponent,
        NotificationComponent,
        ScrollToNotPlayedDirective,
        ClickOutsideDirective,
        TuiTagDirectiveDirective
    ],
    exports: [
        CommonModule,
        RouterModule,
        NavbarComponent,
        NotificationComponent,
        FontAwesomeModule,
        ColorChromeModule,
        ColorTwitterModule,
        TuiRootModule,
        TuiNotificationModule,
        TuiDialogModule,
        TuiTableModule,
        TuiTablePaginationModule,
        TuiAlertModule,
        TuiInputNumberModule,
        TuiFormatNumberPipeModule,
        TuiActionModule,
        TuiInputModule,
        TuiTextAreaModule,
        TuiInputFilesModule,
        TuiInputYearModule,
        TuiDropdownModule,
        TuiCheckboxBlockModule,
        TuiMarkerIconModule,
        TuiAccordionModule,
        TuiTooltipModule,
        TuiStepperModule,
        TuiSidebarModule,
        TuiActiveZoneModule,
        TuiInputPasswordModule,
        TuiPaginationModule,
        TuiComboBoxModule,
        TuiCheckboxLabeledModule,
        TuiToggleModule,
        TuiAppBarModule,
        TuiCalendarModule,
        TuiLoaderModule,
        TuiHintModule,
        TuiTableFiltersModule,
        TuiSvgModule,
        TuiTabsModule,
        TuiButtonModule,
        TuiTabBarModule,
        TuiBadgeModule,
        TuiBadgedContentModule,
        TuiCarouselModule,
        TuiIslandModule,
        TuiScrollbarModule,
        TuiLazyLoadingModule,
        FormsModule,
        ReactiveFormsModule,
        TuiMultiSelectModule,
        TuiSelectModule,
        TuiDataListWrapperModule,
        TuiAvatarModule,
        TuiLabelModule,
        TuiLetModule,
        TuiTagModule,
        TuiDataListModule,
        TuiTextfieldControllerModule,
        TuiDataListWrapperModule,
        TuiElasticContainerModule,
        TuiExpandModule,
        TuiInputModule,
        TuiInputFilesModule,
        TuiComboBoxModule,
        TuiDataListWrapperModule,
        TuiButtonModule,
        TuiLetModule,
        HttpClientModule,
        ScrollToNotPlayedDirective,
        ClickOutsideDirective,
        TuiTagDirectiveDirective,
    ]
})
export class SharedModule { }
